name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Datas
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Gerar a animação do Snake
      - name: Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Passo 3: Listar arquivos do diretório dist para diagnóstico
      - name: List files in dist directory
        run: ls -l dist/

      # Passo 4: Criar diretório assets (onde os arquivos serão movidos)
      - name: Create build directory with permissions
        run: |
          mkdir -p assets
          chmod -R 777 assets  # Garantir permissões para o diretório assets

      # Passo 5: Mover os arquivos gerados do dist para assets
      - name: Move generated files
        run: mv dist/* assets/

      # Passo 6: Commit e push das alterações no repositório
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-snake.svg
          git add assets/github-snake-dark.svg
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
